Libraries for Project

In [74]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

Loading data into pandas dataFrame

In [44]:
credit_data = pd.read_csv('/home/haroonwaheed-19/Downloads/DataSets for ML/credit_data.csv')

In [45]:
credit_data.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

Analyzing DataSets for ML/credit_data

In [46]:
credit_data.describe()

                Time            V1  ...         Amount          Class
count  284807.000000  2.848070e+05  ...  284807.000000  284807.000000
mean    94813.859575  1.168375e-15  ...      88.349619       0.001727
std     47488.145955  1.958696e+00  ...     250.120109       0.041527
min         0.000000 -5.640751e+01  ...       0.000000       0.000000
25%     54201.500000 -9.203734e-01  ...       5.600000       0.000000
50%     84692.000000  1.810880e-02  ...      22.000000       0.000000
75%    139320.500000  1.315642e+00  ...      77.165000       0.000000
max    172792.000000  2.454930e+00  ...   25691.160000       1.000000

[8 rows x 31 columns]

In [4]:
credit_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [47]:
credit_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [6]:
#0-->legit 
#1-->fraud

separating legit and fault transactions data

In [48]:
legit = credit_data[credit_data.Class == 0]
fraud = credit_data[credit_data.Class == 1]

In [49]:
print(legit,legit.shape)
print(fraud,fraud.shape)

            Time         V1         V2  ...       V28  Amount  Class
0            0.0  -1.359807  -0.072781  ... -0.021053  149.62      0
1            0.0   1.191857   0.266151  ...  0.014724    2.69      0
2            1.0  -1.358354  -1.340163  ... -0.059752  378.66      0
3            1.0  -0.966272  -0.185226  ...  0.061458  123.50      0
4            2.0  -1.158233   0.877737  ...  0.215153   69.99      0
...          ...        ...        ...  ...       ...     ...    ...
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[284315 rows x 31 columns] (284315, 31)
            Time        V1        V2  ...       V28  Amount  Class
541        406.0 -2.312227  1.951992  ... -0.143276    0.00      1
623        472.0 -3.043541 -3.157307  ...  0.035764  529.00      1
4920      4462.0 -2.303350  1.759247  ... -0.153029  239.93      1
6108      6986.0 -4.397974  1.358367  ...  0.849573   59.00      1
6329      7519.0  1.234235  3.019740  ...  0.146793    1.00      1
...          ...       ...       ...  ...       ...     ...    ...
279863  169142.0 -1.927883  1.125653  ...  0.147968  390.00      1
280143  169347.0  1.378559  1.289381  ...  0.186637    0.76      1
280149  169351.0 -0.676143  1.126366  ...  0.194361   77.89      1
281144  169966.0 -3.113832  0.585864  ... -0.253700  245.00      1
281674  170348.0  1.991976  0.158476  ... -0.015309   42.53      1

[492 rows x 31 columns] (492, 31)

In [50]:
legit['Amount'].describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [51]:
fraud['Amount'].describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

undersampling the legit data for better performance and model training

In [52]:
legit_sample = legit.sample(n=len(fraud),random_state=42)

In [53]:
print(legit_sample.shape)
print(fraud.shape)

(492, 31)
(492, 31)

creating new dataset after undersampling and shuffling the dataset

In [54]:
balanced_credit_data = pd.concat([legit_sample,fraud],axis=0)
balanced_credit_data = balanced_credit_data.sample(n=len(fraud),random_state=42).reset_index(drop=True)

In [55]:
balanced_credit_data.shape

(492, 31)

In [15]:
balanced_credit_data.head()

      Time         V1        V2         V3  ...       V27       V28  Amount  Class
0  41233.0 -10.645800  5.918307 -11.671043  ...  0.273329 -0.152908    0.00      1
1   1308.0  -1.379848  0.536720   2.647870  ... -0.438189 -0.346731   43.80      0
2  72327.0  -4.198735  0.194121  -3.917586  ...  1.249414 -0.131525  238.90      1
3  78685.0  -0.671155  1.183971   0.793623  ... -0.028254  0.055953    1.30      0
4  31244.0   1.087002  0.065459   0.485043  ...  0.028643  0.007649   18.56      0

[5 rows x 31 columns]

Separating the features and labels of the balanced_credit_data

In [56]:
x = balanced_credit_data.drop(columns='Class',axis=1)
y = balanced_credit_data['Class']

In [57]:
print(x.shape)
print(y.shape)

(492, 30)
(492,)

Splitting the dataset into Test and Train Data

In [68]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

Model Loading and training

In [ ]:
model = LogisticRegression()
model.fit(x_train,y_train)

Predictions on training Data

In [70]:
x_train_predictions = model.predict(x_train)
x_train_accuracy = accuracy_score(x_train_predictions,y_train)
print("Model Trained Accuracy Score : ",x_train_accuracy*100)

Model Trained Accuracy Score :  95.16539440203562

Prediction on testing Data

In [71]:
x_test_predictions = model.predict(x_test)
x_test_accuracy = accuracy_score(x_test_predictions,y_test)
print("Model Test Accuracy Score : ",x_test_accuracy*100)

Model Test Accuracy Score :  92.92929292929293

Making Function to check credit card accuracy on input data

In [72]:
def predictCredit(input):
    input_data = np.asarray(input)
    input_data_reshaped = input_data.reshape(1,-1)
    predictions = model.predict(input_data_reshaped)
    if predictions[0] == 0:
        return "The object is a legitimate transaction"
    else:
        return "The object is a fraudulent transaction"

Calling the function to check whether its legitimate transaction or not

In [76]:
input_data_= [0,1.19185711131486,0.26615071205963,0.16648011335321,0.448154078460911,0.0600176492822243,-0.0823608088155687,-0.0788029833323113,0.0851016549148104,-0.255425128109186,-0.166974414004614,1.61272666105479,1.06523531137287,0.48909501589608,-0.143772296441519,0.635558093258208,0.463917041022171,-0.114804663102346,-0.183361270123994,-0.145783041325259,-0.0690831352230203,-0.225775248033138,-0.638671952771851,0.101288021253234,-0.339846475529127,0.167170404418143,0.125894532368176,-0.00898309914322813,0.0147241691924927,2.69]


predict = predictCredit(input_data_)

print(predict)

The object is a legitimate transaction

/home/haroonwaheed-19/ml-env/lib/python3.12/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(